[2022-06-19 20:22:36,760] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.my_etl manual__2022-06-19T20:17:23.441380+00:00 [queued]>
[2022-06-19 20:22:36,769] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.my_etl manual__2022-06-19T20:17:23.441380+00:00 [queued]>
[2022-06-19 20:22:36,769] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-19 20:22:36,769] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-06-19 20:22:36,769] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-19 20:22:36,797] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): my_etl> on 2022-06-19 20:17:23.441380+00:00
[2022-06-19 20:22:36,806] {standard_task_runner.py:52} INFO - Started process 8475 to run task
[2022-06-19 20:22:36,810] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'my_etl', 'manual__2022-06-19T20:17:23.441380+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/test-dag.py', '--cfg-path', '/tmp/tmp4zgzt1fm', '--error-file', '/tmp/tmpyktbf70p']
[2022-06-19 20:22:36,811] {standard_task_runner.py:80} INFO - Job 232: Subtask my_etl
[2022-06-19 20:22:36,911] {task_command.py:370} INFO - Running <TaskInstance: test.my_etl manual__2022-06-19T20:17:23.441380+00:00 [running]> on host ca189b65812b
[2022-06-19 20:22:37,047] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=my_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-06-19T20:17:23.441380+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-19T20:17:23.441380+00:00
[2022-06-19 20:22:46,567] {logging_mixin.py:115} INFO -                                                 title  ...                                                url
0                      newSoftware Engineering Intern  ...  https://ca.indeed.com/rc/clk?jk=ff663ba3d6b730...
1                 newSoftware Engineer - Intern/Co-op  ...  https://ca.indeed.com/rc/clk?jk=0ee1559c24a34e...
2                           Software Developer Intern  ...  https://ca.indeed.com/rc/clk?jk=92e75e59e3c0a0...
3                           Intern, Software Engineer  ...  https://ca.indeed.com/rc/clk?jk=344a8a2ea0b60d...
4                            Software Engineer Intern  ...  https://ca.indeed.com/company/Rocket-Science-D...
5             Software Development Engineering Intern  ...  https://ca.indeed.com/rc/clk?jk=b37f5967ce21e3...
6            Software Developer Intern, MS, Fall 2022  ...  https://ca.indeed.com/rc/clk?jk=f0c2273cc6ed69...
7            newSoftware Developer Intern (16 months)  ...  https://ca.indeed.com/rc/clk?jk=f0fb76ffbb7377...
8               newJunior Software Developer - Intern  ...  https://ca.indeed.com/company/Convverge-Inc./j...
9                         Software Engineering Intern  ...  https://ca.indeed.com/rc/clk?jk=9868590178c109...
10      newSoftware Developer Intern/Coop - Fall 2022  ...  https://ca.indeed.com/rc/clk?jk=a1975e7f0d2b81...
11  Summer Intern: Professional Services Software ...  ...  https://ca.indeed.com/rc/clk?jk=58bb07dfc3229f...
12                 Software Development Intern - Dash  ...  https://ca.indeed.com/rc/clk?jk=18d2d9e3922781...
13                        Software engineering intern  ...  https://ca.indeed.com/rc/clk?jk=1efee23cac8d06...
14                        Software Engineering Intern  ...  https://ca.indeed.com/rc/clk?jk=fdd23c194a1ec6...

[15 rows x 6 columns]
[2022-06-19 20:22:46,568] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/job_etl.py", line 99, in run_job_etl
    print(engine.query.all())
AttributeError: 'Engine' object has no attribute 'query'
[2022-06-19 20:22:46,582] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=test, task_id=my_etl, execution_date=20220619T201723, start_date=20220619T202236, end_date=20220619T202246
[2022-06-19 20:22:46,614] {standard_task_runner.py:97} ERROR - Failed to execute job 232 for task my_etl ('Engine' object has no attribute 'query'; 8475)
[2022-06-19 20:22:46,662] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-19 20:22:46,705] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
