[2022-06-19 20:18:37,580] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.my_etl manual__2022-06-19T20:18:36.383982+00:00 [queued]>
[2022-06-19 20:18:37,589] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.my_etl manual__2022-06-19T20:18:36.383982+00:00 [queued]>
[2022-06-19 20:18:37,589] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-19 20:18:37,590] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-19 20:18:37,590] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-19 20:18:37,608] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): my_etl> on 2022-06-19 20:18:36.383982+00:00
[2022-06-19 20:18:37,613] {standard_task_runner.py:52} INFO - Started process 8289 to run task
[2022-06-19 20:18:37,617] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'my_etl', 'manual__2022-06-19T20:18:36.383982+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/test-dag.py', '--cfg-path', '/tmp/tmpydz5vs8p', '--error-file', '/tmp/tmpa844lt9f']
[2022-06-19 20:18:37,618] {standard_task_runner.py:80} INFO - Job 230: Subtask my_etl
[2022-06-19 20:18:37,694] {task_command.py:370} INFO - Running <TaskInstance: test.my_etl manual__2022-06-19T20:18:36.383982+00:00 [running]> on host ca189b65812b
[2022-06-19 20:18:37,824] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=my_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-06-19T20:18:36.383982+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-19T20:18:36.383982+00:00
[2022-06-19 20:18:47,479] {logging_mixin.py:115} INFO -                                                 title  ...                                                url
0                                  Software Developer  ...  https://ca.indeed.com/pagead/clk?mo=r&ad=-6NYl...
1                      newSoftware Engineering Intern  ...  https://ca.indeed.com/rc/clk?jk=ff663ba3d6b730...
2                 newSoftware Engineer - Intern/Co-op  ...  https://ca.indeed.com/rc/clk?jk=0ee1559c24a34e...
3                           Software Developer Intern  ...  https://ca.indeed.com/rc/clk?jk=92e75e59e3c0a0...
4                           Intern, Software Engineer  ...  https://ca.indeed.com/rc/clk?jk=344a8a2ea0b60d...
5                            Software Engineer Intern  ...  https://ca.indeed.com/company/Rocket-Science-D...
6             Software Development Engineering Intern  ...  https://ca.indeed.com/rc/clk?jk=b37f5967ce21e3...
7            Software Developer Intern, MS, Fall 2022  ...  https://ca.indeed.com/rc/clk?jk=f0c2273cc6ed69...
8            newSoftware Developer Intern (16 months)  ...  https://ca.indeed.com/rc/clk?jk=f0fb76ffbb7377...
9               newJunior Software Developer - Intern  ...  https://ca.indeed.com/company/Convverge-Inc./j...
10                        Software Engineering Intern  ...  https://ca.indeed.com/rc/clk?jk=9868590178c109...
11      newSoftware Developer Intern/Coop - Fall 2022  ...  https://ca.indeed.com/rc/clk?jk=a1975e7f0d2b81...
12  Summer Intern: Professional Services Software ...  ...  https://ca.indeed.com/rc/clk?jk=58bb07dfc3229f...
13                 Software Development Intern - Dash  ...  https://ca.indeed.com/rc/clk?jk=18d2d9e3922781...
14                        Software engineering intern  ...  https://ca.indeed.com/rc/clk?jk=1efee23cac8d06...

[15 rows x 6 columns]
[2022-06-19 20:18:47,480] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/job_etl.py", line 99, in run_job_etl
    print(engine.query.all())
AttributeError: 'Engine' object has no attribute 'query'
[2022-06-19 20:18:47,493] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=test, task_id=my_etl, execution_date=20220619T201836, start_date=20220619T201837, end_date=20220619T201847
[2022-06-19 20:18:47,525] {standard_task_runner.py:97} ERROR - Failed to execute job 230 for task my_etl ('Engine' object has no attribute 'query'; 8289)
[2022-06-19 20:18:47,568] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-19 20:18:47,617] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
